service: chat-ai-lambda

plugins:
 - 'serverless-plugin-typescript'
 - serverless-plugin-optimize
 - serverless-offline

provider:
 name: aws
 runtime: nodejs18.x
 logs:
  restApi: true
 apiGateway:
  binaryMediaTypes:
    - '*/*'

functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}

package:
  individually: true
  include:
    - .env

custom:
  serverless-offline:
    host: '0.0.0.0'